### ISSUE TITLE
Cannot Use DLL After Compiling

### ISSUE THREAD

**Issue by Songg45** [nsgomez/gzcom-dll#13]
I am unable to use the cheat, "ShowLuaConsole" when I copy the resulting DLL from my compilation into Simcity 4. The cheat works if I just place the already compiled release into the plugins folder, so it's something I am doing wrong.

I have tried Visual Studios 2022 with Windows 10.0.22000, 10.0.17763.0, and 8.1 build tools with v143 and v141 toolsets. I am running Windows 11 Home if that makes a difference too.

Could I get some assistance in successfully compiling this DLL?

**Comment by nsgomez** [comment]
At the bottom of [main.cpp](https://github.com/nsgomez/gzcom-dll/blob/master/gzcom-dll/src/main.cpp), there's an `RZGetComDllDirector` function that the game uses to start the DLL. Right now, it's attached to a dummy director that doesn't do anything.

Take that function, move it to [cGZExtraCheatsDllDirector.cpp](https://github.com/nsgomez/gzcom-dll/blob/master/gzcom-dll/src/cGZExtraCheatsDllDirector.cpp), and change this line:

```cpp
static cGZCustomDllDirector sDirector;
```

to:

```cpp
static cSC4ExtraCheatsPluginCOMDirector sDirector;
```

This isn't documented anywhere so that's my fault.

**Comment by Songg45** [comment]
Good Evening,

I made the above changes, but it still didn't work. I have forked this repo from master just to show my work: https://github.com/Songg45/gzcom-dll-test/commit/c1e5cd6a03bf11d97a3b7146c7578e06bc0b8dc5

Strangely enough, I can compile [PoC: Message Targets](https://github.com/nsgomez/gzcom-dll/releases/tag/1.3-msgtarget)'s code as-is and that works fine.

My project properties:
![image](https://github.com/nsgomez/gzcom-dll/assets/22947231/4d97591d-a6a1-4936-bb30-1b30513c886a)

**Comment by nsgomez** [comment]
I see your change is making changes to the x64 configuration. Make sure you're building for Win32. I just pushed a change to remove the x64 configurations since the game can't load 64-bit DLLs.

**Comment by Songg45** [comment]
Excellent! I switched it to Win32 and I can get the Extra Extra cheats to work.

However, I still cannot get, "ShowLuaConsole" or the IGLE to work even using Extra Cheats. Which DllDirector runs the IGLE?

**Comment by 0xC0000054** [comment]
The in-game UIs are not part of a DLL director, they are scripted windows that the game spawns with the `cIGZUIScriptService`. There is already a [release](https://github.com/nsgomez/gzcom-dll/releases/tag/poc-hidden-uis) that add commands to spawn the following development UIs: ShowLuaConsole, ShowLotConfigChooser, ShowNetworkLotChooser, ShowSimulatorControl, and ShowExemplarDebugger.
